# use SECRET_GITHUB_TOKEN
# see https://github.com/tsl143/itsopensource/blob/master/.github/workflows/gh-pages-publish.yml

name: gh-pages publisher

on:
  push:
    branches: [ master ]

jobs:
  publish-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          cache: 'npm'

      #name: Install dependencies
      - run: npm install
      - run: npm run-script build
      - run: npm test

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
          with:
            branch: gh-pages # The branch the action should deploy to.
            folder: ./ # The folder the action should deploy.
            dist: .vitepress/dist

      - name: Publish release2
        run: git push origin HEAD:gh-pages --force

      - run: git config user.name "hjvogel_test" && git config user.email "hjvogel@gmx.de"
      # name deploy  # add package.json: gh-pages -d public -r https://$GH_TOKEN@github.com/hjvogel/personal-page.git"
      - run: npm run-script deploy
        env:
          GH_TOKEN: ${{secrets.SECRET_GITHUB_TOKEN}}